langchain4j:
  open-ai:
#    local model 0.6b:
#    chat-model:
#      base-url: http://localhost:11434/v1
#      api-key: ""
#      model-name: qwen3:0.6b
#      log-requests: true
#      log-responses: true
#
#    streaming-chat-model:
#      base-url: http://localhost:11434/v1
#      api-key: ""
#      model-name: qwen3:0.6b
#      log-requests: true
#      log-responses: true

#    openrouter model
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: "sk-0fec0d4d97a2487886ad3e7d9c42cc93"
      model-name: qwen-plus
      log-requests: true
      log-responses: true

    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: "sk-0fec0d4d97a2487886ad3e7d9c42cc93"
      model-name: qwen-plus
      log-requests: true
      log-responses: true


    embedding-model:
      base-url: http://localhost:11434/v1
      api-key: ""
      model-name: nomic-embed-text
      log-requests: true
      log-responses: true

  community:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    dev.langchain4j: debug
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coding_service?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
